import { BaseResourceModel } from '../../../../shared/models/base-resource.model';

export class Pedido extends BaseResourceModel {
  constructor(
    public PedidoId?: string,
    public PedidoCodigo?: string,
    public PedidoEmissao?: string,
    public PedidoDesconto?: string,
    public PedidoTransportadora?: string,
    public PedidoTipoFrete?: string,
    public ClienteId?: string,
    public CondicaoPagamentoId?: string,
    public PedidoClienteRepresentante?: string,
    public PedidoObsComercial?: string,
    public PedidoObsInterna?: string,
    public TabelaPrecoId?: string,
    public PedidoEmpresaId?: string,
    public PedidoPedidoCliente?: string,
    public PedidoIdMktPlace?: string,
    public MktPlaceId?: string,
    public PedidoValorFrete?: string,
    public PedidoTipoEntrega?: number,
    public PedidoPesoFrete?: string,
    public PedidoCubagemFrete?: string,
    public PedidoCPFCNPJ?: string,
    public TipoCobrancaId?: string,
    public PedidoNomeCobranca?: string,
    public PedidoEnderecoCobranca?: string,
    public PedidoBairroCobranca?: string,
    public PedidoCidadeCobranca?: string,
    public PedidoCepCobranca?: string,
    public PedidoUFCobranca?: string,
    public PedidoNomeEntrega?: string,
    public PedidoEnderecoEntrega?: string,
    public PedidoBairroEntrega?: string,
    public PedidoCidadeEntrega?: string,
    public PedidoCepEntrega?: string,
    public PedidoUFEntrega?: string,
    public PedidoAvaliacao?: number,
    public PedidoTipoPedido?: number,
    public PedidoOrcamento?: number,
    public PedidoNroOrcamento?: string,
    public CanalVendasId?: string,
    public PedidoCanalVendasAumento?: number,
    public PedidoCanalVendasDesconto?: number,
    public PedidoObsPrazoEntrega?: string,
    public PedidoEmpcod?: number,
    public PedidoCaixa?: string,
    public PedidoCaixaCancelamento?: string,
    public PedidoAgendamento?: string,
    public PedidoDescontoValor?: string,
    public PedidoNotaFiscalId?: string,
    public PedidoChaveAcesso?: string,
    public PedidoCadastroUsuario?: string,
    public PedidoCadastroData?: string,
    public PedidoCadastroHora?: string,
    public PedidoAlteracaoUsuario?: string,
    public PedidoAlteracaoData?: string,
    public PedidoAlteracaoHora?: string,
    public PedidoLiberacaoUsuario?: string,
    public PedidoLiberacaoData?: string,
    public PedidoLiberacaoHora?: string,
    public PedidoLiberacaoObs?: string,
    public PedidoLiberacaoFaturamentoUsuario?: string,
    public PedidoLiberacaoFaturamentoData?: string,
    public PedidoLiberacaoFaturamentoHora?: string,
    public PedidoLiberacaoFaturamentoStatus?: number,
    public PedidoliberacaoFaturamentoObs?: string,
    public PedidoTotalValor?: string,
    public PedidoPendente?: boolean,
    public PedidoSenhaVendedor?: string,
    public PedidoRepresentanteId?: string
  ) {
    super();
    this.id = this.PedidoId;
  }

  static fromJson(jsonData: any): Pedido {
    return Object.assign(new Pedido(jsonData.PedidoId), jsonData);
  }
}
